CREATE TABLE IF NOT EXISTS dbo.credentials
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL DEFAULT gen_random_uuid(),
    tenant_id     BIGINT       NOT NULL REFERENCES dbo.tenants(id),
    email         VARCHAR(254) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(50)  NOT NULL DEFAULT 'User',
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at_utc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    updated_at_utc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT uq_credentials_email UNIQUE (email)
);
