<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Authentication.Domain/Authentication.Domain.csproj" />
    <ProjectReference Include="../../Shared.Infrastructure/Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Otp.NET" />
  </ItemGroup>

</Project>
