<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="$(CommonRoot)Common.Web/Common.Web.csproj" />
    <ProjectReference Include="$(CommonRoot)Common.Messaging/Common.Messaging.csproj" />
    <ProjectReference Include="../../../Shared/Shared.Web/Shared.Web.csproj" />
    <ProjectReference Include="../Tenancy.Application/Tenancy.Application.csproj" />
    <ProjectReference Include="../Tenancy.Contracts/Tenancy.Contracts.csproj" />
  </ItemGroup>

</Project>
