CREATE TABLE IF NOT EXISTS dbo.Branches
(
    Id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PublicId     UUID         NOT NULL DEFAULT gen_random_uuid(),
    TenantId     BIGINT       NOT NULL REFERENCES dbo.Tenants(Id),
    Name         VARCHAR(200) NOT NULL,
    IsActive     BOOLEAN      NOT NULL DEFAULT TRUE,
    CreatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    UpdatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now()))
);
