CREATE TABLE IF NOT EXISTS dbo.user_profiles
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id      UUID         NOT NULL,
    tenant_id      BIGINT       NOT NULL REFERENCES dbo.tenants(id),
    full_name      VARCHAR(200) NOT NULL,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at_utc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    updated_at_utc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT uq_user_profiles_public_id UNIQUE (public_id)
);
