CREATE TABLE IF NOT EXISTS dbo.UserProfiles
(
    Id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PublicId     UUID         NOT NULL,
    TenantId     BIGINT       NOT NULL REFERENCES dbo.Tenants(Id),
    BranchId     BIGINT       NOT NULL REFERENCES dbo.Branches(Id),
    FullName     VARCHAR(200) NOT NULL,
    IsActive     BOOLEAN      NOT NULL DEFAULT TRUE,
    CreatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    UpdatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT UQ_UserProfiles_PublicId UNIQUE (PublicId)
);
