CREATE TABLE IF NOT EXISTS dbo.ExampleUsers
(
    Id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PublicId     UUID         NOT NULL DEFAULT gen_random_uuid(),
    FullName     VARCHAR(200) NOT NULL,
    Email        VARCHAR(254) NOT NULL,
    Department   VARCHAR(100) NOT NULL DEFAULT '',
    Notes        TEXT         NOT NULL DEFAULT '',
    IsActive     BOOLEAN      NOT NULL DEFAULT TRUE,
    CreatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    UpdatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT UQ_ExampleUsers_Email UNIQUE (Email)
);
