CREATE TABLE IF NOT EXISTS dbo.Tenants
(
    Id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PublicId     UUID         NOT NULL DEFAULT gen_random_uuid(),
    Name         VARCHAR(200) NOT NULL,
    Slug         VARCHAR(100) NOT NULL,
    IsActive     BOOLEAN      NOT NULL DEFAULT TRUE,
    CreatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    UpdatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT UQ_Tenants_Slug UNIQUE (Slug)
);
