CREATE TABLE IF NOT EXISTS dbo.Users
(
    Id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PublicId     UUID         NOT NULL DEFAULT gen_random_uuid(),
    TenantId     BIGINT       NOT NULL REFERENCES dbo.Tenants(Id),
    BranchId     BIGINT       NOT NULL REFERENCES dbo.Branches(Id),
    FullName     VARCHAR(200) NOT NULL,
    Email        VARCHAR(254) NOT NULL,
    PasswordHash VARCHAR(100) NOT NULL,
    Role         VARCHAR(50)  NOT NULL DEFAULT 'User',
    IsActive     BOOLEAN      NOT NULL DEFAULT TRUE,
    CreatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    UpdatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT UQ_Users_Email UNIQUE (Email)
);
