CREATE TABLE IF NOT EXISTS dbo.RefreshTokens
(
    Id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId       BIGINT       NOT NULL REFERENCES dbo.Users(Id),
    Token        VARCHAR(256) NOT NULL,
    ExpiresAtUtc TIMESTAMP(0) NOT NULL,
    IsRevoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    CreatedAtUtc TIMESTAMP(0) NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT UQ_RefreshTokens_Token UNIQUE (Token)
);
