<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Shared/Shared.Kernel/Shared.Kernel.csproj" />
    <ProjectReference Include="../../src/Shared/Shared.Web/Shared.Web.csproj" />
    <ProjectReference Include="../../src/Shared/Shared.Infrastructure/Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
